title: "DSPy: The Complete Guide"
author: Dustin Ober
copyright: "2024"
# logo: content/images/logo.png
repository:
  url: https://github.com/dustinober/Ebook_DSPy
  path_to_book: ""
  branch: main
launch_buttons:
  notebook_interface: "classic"
  colab_url: "https://colab.research.google.com"
  binderhub_url: ""
  thebe: false
execute:
  execute_notebooks: "off"
  timeout: 300
  allow_errors: false
exclude_patterns:
  - venv
  - planning
  - src
  - tests
  - README.md
  - todo.md
  - requirements.txt
  - .github
  - .gitignore
sphinx:
  extra_extensions:
    - sphinx_copybutton
  config:
    html_theme_options:
      use_download_button: true
      use_fullscreen_button: true
